[features]
seeds = false
skip-lint = false


[programs.devnet]
janecek_method = "Fnambs3f1XXoMmAVc94bf8t6JDAxmVkXz85XU4v2edph"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
