[package]
name = "program_client"
version = "0.1.0"
edition = "2018"

[dependencies]
trdelnik-client = "0.3.0"

[dependencies.janecek_method]
path = "../programs/janecek_method"
features = ["no-entrypoint"]
